extends:
  - 'eslint:recommended' # http://eslint.org/docs/rules/
  - 'bestpratices' # https://github.com/sonnyp/eslint-config-bestpratices#readme

env:
  node: true

rules:
  # Possible Errors
  # http://eslint.org/docs/rules/#possible-errors
  # recommended are covered by eslint:recommended
  no-extra-parens: 2 # http://eslint.org/docs/rules/no-extra-parens
  no-unexpected-multiline: 2 # http://eslint.org/docs/rules/no-unexpected-multiline
  valid-jsdoc: 2 # http://eslint.org/docs/rules/valid-jsdoc

  # Best Pratices
  # http://eslint.org/docs/rules/#best-practices
  # covered by eslint-config-bestpratices

  # Strict Mode
  # http://eslint.org/docs/rules/#strict-mode
  strict: [2, global]

  # Variables
  # http://eslint.org/docs/rules/#variables
  init-declarations: 2 # http://eslint.org/docs/rules/init-declarations
  no-catch-shadow: 0 # http://eslint.org/docs/rules/no-catch-shadow
  # 'no-delete-var' covered by eslint:recommended http://eslint.org/docs/rules/no-catch-shadow
  no-label-var: 2 # http://eslint.org/docs/rules/no-label-var
  no-shadow-restricted-names: 2 # http://eslint.org/docs/rules/no-shadow-restricted-names
  no-shadow: 2 # http://eslint.org/docs/rules/no-shadow
  no-undef-init: 2 # http://eslint.org/docs/rules/no-undef-init
  # 'no-undef' covered by eslint:recommended http://eslint.org/docs/rules/no-undef
  no-undefined: 2 # http://eslint.org/docs/rules/no-undefined
  # 'no-unused-vars' covered by eslint:recommended http://eslint.org/docs/rules/no-unused-vars
  no-use-before-define: 2 # http://eslint.org/docs/rules/no-use-before-define

  # Node.js and CommonJS
  # http://eslint.org/docs/rules/#nodejs-and-commonjs
  callback-return: 2 # http://eslint.org/docs/rules/callback-return
  global-require: 2 # http://eslint.org/docs/rules/global-require
  handle-callback-err: 2 # http://eslint.org/docs/rules/handle-callback-err
  no-mixed-requires: [2, {grouping: true}] # http://eslint.org/docs/rules/no-mixed-requires
  no-new-require: 2 # http://eslint.org/docs/rules/no-new-require
  no-path-concat: 2 # http://eslint.org/docs/rules/no-path-concat
  no-process-exit: 2 # http://eslint.org/docs/rules/no-process-exit
  no-restricted-modules: 2 # http://eslint.org/docs/rules/no-restricted-modules
  no-sync: 2 # http://eslint.org/docs/rules/no-sync

  # Stylistic Issues
  # http://eslint.org/docs/rules/#stylistic-issues
  # TODO

  # ECMAScript 6
  # http://eslint.org/docs/rules/#ecmascript-6
  # TODO
